### ISSUE TITLE
Providing the indent-blankline configuration

### ISSUE THREAD

**Issue by sleiphir** [felipeagc/fleet-theme-nvim#1]
I have never used indent-blankline before and I think it would be nice to have the indent-blankline configuration used in the screenshot showcasing the color scheme. I spent a few hours reading online and configuring mine using the doc, I have pretty much the same thing now except I can't find a way to position the scope at the baseline instead of the indent level like you did it

**Comment by felipeagc** [comment]
Ah, what's on the screenshot is actually from [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim). I don't actually use indent-blankline, so I don't know if it's possible to make it look like that unfortunately.

**Comment by sleiphir** [comment]
I see I was mistken, thanks I will close the issue
