### ISSUE TITLE
Include tab color highlight groups

### ISSUE THREAD

**Issue by sleiphir** [felipeagc/fleet-theme-nvim#2]
When using vim tabs,
:tabnew <file> 

The color of the top bar is off, the text appears white on a light gray background. It would be nice to include coloration for these highlight groups: TabLine, TabLineFill, TabLineSel

![image](https://github.com/felipeagc/fleet-theme-nvim/assets/21320365/16a4c211-1c23-4e54-b37d-af8a9d30ce6d)

**Comment by felipeagc** [comment]
Totally missed this! Added tab colors in [3d2dfd8](https://github.com/felipeagc/fleet-theme-nvim/commit/3d2dfd88583a4fa2c73d8244229490e6d021ceb2).

Should look like this:
![image](https://github.com/felipeagc/fleet-theme-nvim/assets/17355488/b2726763-b136-423b-9524-fccd4c65c0b5)
