### ISSUE TITLE
Add highlight for WinSeparator

### ISSUE THREAD

**Issue by ghost** [felipeagc/fleet-theme-nvim#3]
Nvim is deprecating VertSplit and moving to WinSeparator for window borders in 0.10. By default, WinSeparator links to normal which does not look great for most colorschemes.

**Comment by felipeagc** [comment]
Fixed in [df10a0e](https://github.com/felipeagc/fleet-theme-nvim/commit/df10a0e0021d3267eb7c7104107988e4fb977b32).
